# Normal Distribution Problems

In [356]:
#python libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
from scipy.stats import ttest_1samp, wilcoxon, shapiro
from statsmodels.stats.power import ttest_power
import scipy.stats as stats
# another way to import "from scipy.stats import norm" no prefix needed
from scipy.stats import chisquare , chi2_contingency

In [2]:
#food packet mean wt is 125g with sd= 15.5 g, what is the  chance of customer getting a pack less than
#100g and getting pack above 135g

# Z score

z= (100-125)/15.5
z

-1.6129032258064515

In [5]:
stats.norm.cdf(z) #there is a 5.3% chance that person gets packet <100g

0.05338276713404089

In [6]:
#z score for 135

z1= (135-125)/15.5

In [7]:
z1

0.6451612903225806

In [8]:
1-stats.norm.cdf(z1) #25.9% chance of getting a packet above wt 135g

0.25941133433509533

In [9]:
#calculate for >123g and <128gm
# z score for 123

z2= (123-125)/ 15.5
z2

-0.12903225806451613

In [11]:
# z score for 128
z3= (128-125)/15.5
z3

0.1935483870967742

In [15]:
a= stats.norm.cdf(z2)
a

0.448666061968402

In [16]:
b= stats.norm.cdf(z3)
b

0.5767352425179979

In [14]:
c=b-a
c  # 12.8% chances that the consumer is getting the mean weight, Producer's loss

0.12806918054959593

# Test for Proportionality

In [17]:
pwd C:\Users\ASUS\Desktop\great learning\week3

'C:\\Users\\ASUS\\Desktop\\great learning\\week3'

In [329]:
A=pd.read_table('HR.txt', index_col=0)

In [51]:
B=pd.crosstab(A['Attrition'], A['Gender']) #contingency table
B

Gender       1    2
Attrition          
No         732  501
Yes        150   87

whenever we have to do proportionality test, first we need a contingency table. Here, we do not check 
if the data is normal or not. We have categorical variables for which we need Binomial and Poisson 
Distribution.

In [219]:
x1= B.iloc[1,0]
x2= B.iloc[1,1]
n1= B.iloc[:,0].sum()
n2= B.iloc[:, 1].sum()
n1, n2, x1, x2


(882, 588, 150, 87)

In [191]:
p1= x1/n1
p2= x2/n2

p_pool= (x1+x2)/(n1+n2)

In [192]:
p_pool

0.16122448979591836

In [193]:
a=p1-p2
a

0.022108843537414963

In [194]:
b= np.sqrt(p_pool*(1-p_pool)*(1/n1 + 1/n2))

In [195]:
z_data =a/b
z_data

1.1292547809155016

In [196]:
pval=2*(1-stats.norm.cdf(abs(z_data)))
pval

0.2587903704911598

In [257]:
# if i want to write the above calculations in a function as there is no predefined func in python

def twosampz(x1,x2,n1,n2):
    p1=x1/n1
    p2=x2/n2
    pp=(x1+x2)/(n1+n2)
    zdata=(p1-p2)/(np.sqrt(pp*(1-pp)*(1/n1 + 1/n2)))
    pval=2*(1-stats.norm.cdf(abs(zdata)))
    return round(zdata,3),pval

In [221]:
z,p=twosampz(x1,x2,n1,n2)

In [222]:
print(z)

1.129


## Proportion Test with migraine.csv

In [200]:
m=pd.read_csv('Migraine.csv', index_col=0)

In [201]:
m.head()

id  time  dos hatype  age  airq  medication headache  Gender
1   1   -11  753   Aura   30   9.0  continuing      yes  female
2   1   -10  754   Aura   30   7.0  continuing      yes  female
3   1    -9  755   Aura   30  10.0  continuing      yes  female
4   1    -8  756   Aura   30  13.0  continuing      yes  female
5   1    -7  757   Aura   30  18.0  continuing      yes  female

In [202]:
m['hatype'].value_counts()

No Aura    1985
Aura       1710
Mixed       457
Name: hatype, dtype: int64

In [203]:
#check whether the proportion of headache among male and female patients in magraine.csv is same 
# statically different?



categorical variables , so we will perform z test.

Ho---> proportion of males with headache= proportion of female with headache

Ha--->not equal

In [204]:
#to know the no. of females and males who visited the clinic

m['Gender'].value_counts()

female    3545
male       607
Name: Gender, dtype: int64

In [205]:
m['headache'].value_counts()

yes    2666
no     1486
Name: headache, dtype: int64

In [206]:
m1=pd.crosstab(m['headache'], m['Gender']) #contingency table
m1

Gender    female  male
headache              
no          1266   220
yes         2279   387

In [223]:
n2=m1.iloc[:,0].sum()
n1=m1.iloc[:,1].sum()
n1,n2

(607, 3545)

In [224]:
m1['male'].sum()

607

In [225]:
m1["female"].sum()

3545

In [226]:
x2= m1.iloc[1,0]
x1=m1.iloc[1,1]
x1,x2

(387, 2279)

In [227]:
p1=x1/n1 #males
p1

0.6375617792421746

In [228]:
p2= x2/n2 #females
p2

0.6428772919605078

In [229]:
x1,x2,n1,n2

(387, 2279, 607, 3545)

In [230]:
z,p= twosampz(x1,x2,n1,n2)

print("Z data=", z)
print("P value=", p)

Z data= -0.252
P value= 0.8007


Inference:
High p value>0.05 suggest, fails to reject Ho, which implies, the proportion of male and female patients having headache
more less the same.

### Exercise
#### Load heart.csv and check proportion of male and female having heart disease is same or not?

In [232]:
h=pd.read_csv('heart.csv', index_col=0)

In [233]:
h.head()

gender  chest_pain  blood_pressure  cholestoral  blood_sugar   ecg  \
age                                                                       
70        1           4             130          322             0    2   
67        0           3             115          564             0    2   
57        1           2             124          261             0    0   
64        1           4             128          263             0    0   
74        0           2             120          269             0    2   

     heart_rate   exercise   oldpeak  slope  vessels   thal  disease  
age                                                                   
70           109          0      2.4      2        3      3        2  
67           160          0      1.6      2        0      7        1  
57           141          0      0.3      1        0      7        2  
64           105          1      0.2      2        1      7        1  
74           121          1      0.2      1        1      3        1

In [235]:
h['gender'].value_counts() # 0= male, 1= female

1    183
0     87
Name: gender, dtype: int64

In [236]:
h['disease'].value_counts()  #1= not having disease, 2= having disease

1    150
2    120
Name: disease, dtype: int64

In [238]:
h1=pd.crosstab(h['disease'], h['gender'])
h1

gender    0    1
disease         
1        67   83
2        20  100

In [244]:
n1= h1.iloc[:,0].sum()
n2=h1.iloc[:,1].sum()
n1, n2

(87, 183)

In [247]:
x1=h1.iloc[1,0]
x2=h1.iloc[1,1]
x1, x2

(20, 100)

In [250]:
p1= x1/n1 #percentage of male with disease=22.9%
p2=x2/n2 #percentage of female with disease= 54.6%
p1,p2

(0.22988505747126436, 0.546448087431694)

In [258]:
zd,pd=twosampz(x1,x2,n1,n2)

In [259]:
zd

-4.892

In [260]:
pd

9.979046911023914e-07

Strong evidence to reject Ho(no. of females having heart disease is equal to that of no. of males), with 100% confidence we can say more e has higher risk of heart disease than male

# CHI SQUARE TEST

Also called goodness of fit and test of dependency.

In [298]:
ob= np.array((410,340,250,95,85,70))

In [299]:
ob

array([410, 340, 250,  95,  85,  70])

In [294]:
ex= np.array((404,340,256,101,85,64))
ex

array([404, 340, 256, 101,  85,  64])

In [310]:
chi_val=(((ob-ex)**2)/ex).sum()

In [311]:
chi_val

1.1486695544554455

In [306]:
# using built in functions

ob1= pd.Series([410,340,250,95,85,70])
ex1=pd.Series([404,340,256,101,85,64])

In [307]:
#represent your cross tab(observed count)

CT= pd.crosstab(ob1,ex1)

In [308]:
CT

col_0  64   85   101  256  340  404
row_0                              
70       1    0    0    0    0    0
85       0    1    0    0    0    0
95       0    0    1    0    0    0
250      0    0    0    1    0    0
340      0    0    0    0    1    0
410      0    0    0    0    0    1

In [319]:
#Ho-> the proportion of people with healthy mild and severe are equal
#Ha->atleast one of the groups' are not equal





df=pd.DataFrame(np.array([[410,340,250],[95,85,70]]))
df.columns=['Healthy','Mild','Severe']
df.index= ['Sc-1', 'Sc-2']
df

Healthy  Mild  Severe
Sc-1      410   340     250
Sc-2       95    85      70

In [322]:
ch_val, p_val,nrow,EC=chi2_contingency(df)

In [323]:
print(ch_val)

1.1486695544554455


In [324]:
print(p_val)

0.5630793174318253


In [325]:
print(nrow)

2


In [326]:
print(EC)

[[404. 340. 256.]
 [101.  85.  64.]]


p val>0.05 which implies, we fail to reject the null hypothesis Ho
that means, the proportion of samples though not equal numerically but are statistically same.
Therefore, these three column values are dependent on each other

In [330]:
A.head()

Attrition  Age  BusinessTravel  DailyRate  Department  \
Individual                                                          
Ind1              Yes   41               1       1102           1   
Ind2               No   49               2        279           2   
Ind3              Yes   37               1       1373           2   
Ind4               No   33               2       1392           2   
Ind5               No   27               1        591           2   

             DistanceFromHome  Education  EducationField  EmployeeCount  \
Individual                                                                
Ind1                        1          2               1              1   
Ind2                        8          1               1              1   
Ind3                        2          2               6              1   
Ind4                        3          4               1              1   
Ind5                        2          1               2              1   

             EmployeeNumber          ...           RelationshipSatisfaction  \
Individual                           ...                                      
Ind1                      1          ...                                  1   
Ind2                      2          ...                                  4   
Ind3                      4          ...                                  2   
Ind4                      5          ...                                  3   
Ind5                      7          ...                                  4   

             StandardHours  StockOptionLevel  TotalWorkingYears  \
Individual                                                        
Ind1                    80                 0                  8   
Ind2                    80                 1                 10   
Ind3                    80                 0                  7   
Ind4                    80                 0                  8   
Ind5                    80                 1                  6   

             TrainingTimesLastYear  WorkLifeBalance  YearsAtCompany  \
Individual                                                            
Ind1                             0                1               6   
Ind2                             3                3              10   
Ind3                             3                3               0   
Ind4                             3                3               8   
Ind5                             3                3               2   

             YearsInCurrentRole  YearsSinceLastPromotion  YearsWithCurrManager  
Individual                                                                      
Ind1                          4                        0                     5  
Ind2                          7                        1                     7  
Ind3                          0                        0                     0  
Ind4                          7                        3                     0  
Ind5                          2                        2                     2  

[5 rows x 34 columns]

In [331]:
A['Department'].value_counts() #1- sales 2- prodn 3-marketing

2    961
1    446
3     63
Name: Department, dtype: int64

In [332]:
A['Attrition'].value_counts()

No     1233
Yes     237
Name: Attrition, dtype: int64

In [336]:
C=pd.crosstab(A['Attrition'], A['Department'])
C

Department    1    2   3
Attrition               
No          354  828  51
Yes          92  133  12

In [337]:
ch_val, p_val,nrow,EC=chi2_contingency(C)

In [339]:
print(ch_val)
print(p_val)


10.79600732241067
0.004525606574479633


In [340]:
print(EC)

[[374.09387755 806.06326531  52.84285714]
 [ 71.90612245 154.93673469  10.15714286]]


Inference:
we reject Ho, as p value is <0.05 which implies that no. of people who left the company from each department are not equal.Attrition number in diiferent departments are independent of each other. Larger the Chi square value, Ha will be true and vice versa
    
if we calculate the percentage of people who left we can say, attrition rate of sales and marketing is more than that of prodn

In [353]:
chi2_contingency(C)

(10.79600732241067,
 0.004525606574479633,
 2,
 array([[374.09387755, 806.06326531,  52.84285714],
        [ 71.90612245, 154.93673469,  10.15714286]]))

In [357]:
chisquare(A['Department'].value_counts())

Power_divergenceResult(statistic=828.7877551020408, pvalue=1.074052833315366e-180)

In [358]:
#Load the migraine dataset and  check whether there is a dependency exist between type of migraine with respect to
#male and female

In [360]:
m=pd.read_csv('Migraine.csv', index_col=0)

m.head()

id  time  dos hatype  age  airq  medication headache  Gender
1   1   -11  753   Aura   30   9.0  continuing      yes  female
2   1   -10  754   Aura   30   7.0  continuing      yes  female
3   1    -9  755   Aura   30  10.0  continuing      yes  female
4   1    -8  756   Aura   30  13.0  continuing      yes  female
5   1    -7  757   Aura   30  18.0  continuing      yes  female

In [361]:
m1= pd.crosstab(m["Gender"], m["hatype"])

In [362]:
m1

hatype  Aura  Mixed  No Aura
Gender                      
female  1593    291     1661
male     117    166      324

In [368]:
#Ho--> dependency exist between type of migraine with respect to
#male and female

#Ha--> dependency doesnt exist

In [369]:
# First   we ll check for one dimension 

chisquare(m["hatype"].value_counts())

Power_divergenceResult(statistic=958.6748554913295, pvalue=6.705021277393725e-209)

In [370]:
chisquare(m["Gender"].value_counts())

Power_divergenceResult(statistic=2078.960500963391, pvalue=0.0)

In [371]:
chi2_contingency(m1)

(259.94962922327386,
 3.569893234435195e-57,
 2,
 array([[1460.00722543,  390.18906551, 1694.80370906],
        [ 249.99277457,   66.81093449,  290.19629094]]))

In [364]:
ch_val, p_val,nrow,EC=chi2_contingency(m1)

In [365]:
print(ch_val)

259.94962922327386


In [366]:
print(p_val)

3.569893234435195e-57


In [367]:
print(EC)

[[1460.00722543  390.18906551 1694.80370906]
 [ 249.99277457   66.81093449  290.19629094]]


In [380]:
m['Gender'].value_counts()

female    3545
male       607
Name: Gender, dtype: int64

In [381]:
#percentage table

df1=pd.DataFrame(np.array([[45,8,46.8],[19,27,53]]))
df1.columns=['Aura','Mixed','No Aura']
df1.index= ['female', 'male']
df1

Aura  Mixed  No Aura
female  45.0    8.0     46.8
male    19.0   27.0     53.0

From the above we can infere,there is a significant difference btw type of migraine wrt Gender

In [382]:
m1

hatype  Aura  Mixed  No Aura
Gender                      
female  1593    291     1661
male     117    166      324

males are highly sensitive to mixed type migraine when comared to female and females are highly sensitive to  aura type
migraine

In [377]:
n_aura= m1.iloc[:,0].sum()
n_noaura=m1.iloc[:,1].sum()
n_mixed=m1.iloc[:,2].sum()
n_aura, n_noaura, n_mixed

(1710, 457, 1985)

## Fair Pay Dataset

In [387]:
F=pd.read_csv('fair_pay_data.csv', index_col=0)

In [388]:
F.head()

department        salary new_hire job_level
employee_id                                              
1                  Sales  103263.63550       No  Salaried
2            Engineering   80708.64104       No    Hourly
4            Engineering   60737.04786      Yes    Hourly
5            Engineering   99116.32328      Yes  Salaried
7            Engineering   51021.64386       No    Hourly

In [390]:
F["job_level"].value_counts()

Hourly      1039
Salaried     326
Manager      105
Name: job_level, dtype: int64

In [391]:
F["department"].value_counts()

Engineering    961
Sales          446
Finance         63
Name: department, dtype: int64

is there any dependency between the nature of job level and department?

In [392]:
f1=pd.crosstab(F['job_level'],F['department'])
f1

department  Engineering  Finance  Sales
job_level                              
Hourly              688       41    310
Manager              66        6     33
Salaried            207       16    103

In [394]:
ch_val, p_val,nrow,EC=chi2_contingency(f1)

In [395]:
print(ch_val, p_val)

1.7618006349813817 0.7794632298921784


Here, we have a high p value, which means we fail to reject Ho, which means there is no dependency btw type of job level and deptt.
The type of people hired are equal in all departments