In [5]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
# importing ploting libraries
import matplotlib.pyplot as plt   
#importing seaborn for statistical plots
import seaborn as sns
#Let us break the X and y dataframes into training set and test set. For this we will use
#Sklearn package's data splitting function which is based on random function
from sklearn.model_selection import train_test_split
import numpy as np
# calculate accuracy measures and confusion matrix
from sklearn import metrics
import statsmodels.formula.api as smf
%matplotlib inline
from sklearn import preprocessing

In [20]:
A=pd.read_csv('iris.csv',names=['SepalL','SepalW','PetalL','PetalW','Class'])
A['Class'].value_counts()

Iris-virginica     50
Iris-setosa        50
Iris-versicolor    50
Name: Class, dtype: int64

In [14]:
import copy
B=copy.deepcopy(A)
B.head()

SepalL  SepalW  PetalL  PetalW  Class
0     5.1     3.5     1.4     0.2      0
1     4.9     3.0     1.4     0.2      0
2     4.7     3.2     1.3     0.2      0
3     4.6     3.1     1.5     0.2      0
4     5.0     3.6     1.4     0.2      0

In [17]:
le=preprocessing.LabelEncoder()
le.fit(B['Class'])
B['Class']=le.transform(B['Class'])

In [23]:
x=B[['SepalL','SepalW','PetalL','PetalW']]
y=B[['Class']]

In [19]:
B['Class'].value_counts()

2    50
1    50
0    50
Name: Class, dtype: int64

In [24]:
LR=LogisticRegression()
LR.fit(x,y)
y_pred=LR.predict(x)

/usr/local/anaconda/python3/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [25]:
acc=metrics.accuracy_score(y,y_pred)
print(acc)

0.96


In [26]:
cm=metrics.confusion_matrix(y,y_pred)
print(cm)

[[50  0  0]
 [ 0 45  5]
 [ 0  1 49]]


In [27]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       2, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [29]:
cr=metrics.classification_report(y,y_pred)
print(cr)

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        50
          1       0.98      0.90      0.94        50
          2       0.91      0.98      0.94        50

avg / total       0.96      0.96      0.96       150

